//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 10:57:59 PM EST 
//

package com.cvberry.berrypim.data;

import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * 
 *  Defines all information relating to a "contact" (someone I know
 *  and want to store information for).
 *
 */
public class Contact {

    @NotNull
    protected String name;

    protected List<String> tags;
    protected String birthday;
    protected List<PhoneNumber> phoneNumbers;
    protected List<TypeAnnotatedString> emails;
    protected List<TypeAnnotatedString> addresses;
    protected String note;

    public Contact(String name, List<String> tags, String birthday, List<PhoneNumber> phoneNumbers,
                   List<TypeAnnotatedString> emails, List<TypeAnnotatedString> addresses, String note) {
        this.name = name;
        this.tags = tags;
        this.birthday = birthday;
        this.phoneNumbers = phoneNumbers;
        this.emails = emails;
        this.addresses = addresses;
        this.note = note;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        if(name==null) {
            return;
        }

        this.name = name;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public List<PhoneNumber> getPhoneNumbers() {
        return phoneNumbers;
    }

    public void setPhoneNumbers(List<PhoneNumber> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

    public List<TypeAnnotatedString> getEmails() {
        return emails;
    }

    public void setEmails(List<TypeAnnotatedString> emails) {
        this.emails = emails;
    }

    public List<TypeAnnotatedString> getAddresses() {
        return addresses;
    }

    public void setAddresses(List<TypeAnnotatedString> addresses) {
        this.addresses = addresses;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    /**
     * name and birthday define "equality"
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Contact contact = (Contact) o;

        if (!name.equals(contact.name)) return false;
        if (birthday != null ? !birthday.equals(contact.birthday) : contact.birthday != null) return false;
        return true;
    }

    @Override
    public int hashCode() {
        int result = name.hashCode();
        result = 31 * result + (birthday != null ? birthday.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Contact{" +
                "name='" + name + '\'' +
                ", tags=" + tags +
                ", birthday='" + birthday + '\'' +
                ", phoneNumbers=" + phoneNumbers +
                ", emails=" + emails +
                ", addresses=" + addresses +
                ", note='" + note + '\'' +
                '}';
    }
}

